name: Build Automation for Backend Application

on:
  pull_request:
    branches: [ develop, release, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: Backend

    - name: Build with Gradle
      run: ./gradlew clean bootJar
      working-directory: Backend

    - name: Run Docker-compose
      run: docker-compose up --build

    - name: Static code analysis
      run: ./gradlew sonarqube
      working-directory: Backend

    - name: Unit tests
      run: ./gradlew test --tests "com.example.*"
      working-directory: Backend
